# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: python

sudo: required

services:
  - docker

env: SH="docker exec -t ubuntu-test bash -c"

before_install:
  - docker run -d --name ubuntu-test -e LC_ALL="en_US.UTF-8" -e LANG="en_US.UTF-8" -v $(pwd):/travis -w /travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - $SH "apt-get update"
  - $SH "apt-get install -y locales"
  - $SH "locale-gen en_US.UTF-8"
  - $SH "apt-get install -y python3"
  - $SH "apt-get install -y python3-pip"
  - $SH "apt-get install -y python-dbus"
  - $SH "apt-get install -y python3-dbus"
  - $SH "apt-get install -y python-gi"
  - $SH "apt-get install -y python3-gi"
  - $SH "python3 -m pip install -q --upgrade pip"
  - $SH "python3 -m pip install -q pycodestyle"
  - $SH "python3 -m pip install -q 'coverage>4.0,<4.4'"
  - $SH "python3 -m pip install -q codecov"

script:
  # Shared
  - $SH "coverage run -m unittest -v tests.test_tools"
  - $SH "coverage run --append -m unittest -v tests.test_dbus_tools"
  - $SH "coverage run --append -m unittest -v tests.test_async_tools"
  # Level 100
  - $SH "coverage run --append -m unittest -v tests.test_adapter"
  - $SH "coverage run --append -m unittest -v tests.test_advertisement"
  - $SH "coverage run --append -m unittest -v tests.test_device"
  - $SH "coverage run --append -m unittest -v tests.test_gatt"
  # Level 10
  - $SH "coverage run --append -m unittest -v tests.test_broadcaster"
  - $SH "coverage run --append -m unittest -v tests.test_central"
  - $SH "coverage run --append -m unittest -v tests.test_peripheral"
  # Level 1
  - $SH "coverage run --append -m unittest -v tests.test_eddystone"
  - $SH "coverage run --append -m unittest -v tests.test_microbit"
  # Examples (Level 1)
  - $SH "coverage run --append -m unittest -v tests.test_adapter_example"

after_success:
  #
  - $SH "codecov"
